config/routes.rb
Rails.application.routes.draw do
  get "tasks", to: "tasks#list"
  post "tasks", to: "tasks#create"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#find", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

# can try resources

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:find, :edit, :update, :destroy]

  def list
    @tasks = Task.all
    # raise
  end

  def find
    @task.completed ? @task_phrase = "completed" : @task_phrase = "not completed yet"
    # raise
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require("task").permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params["id"].to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  Completed: <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to tasks", tasks_path%>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/find.html.erb
<h1><%= @task.title %></h1>
<h4><%= @task.details %></h4>
<%= link_to "Edit this task", task_edit_path(@task)%>
<div>
  <input type="checkbox" name="completed" <%= "checked" if @task.completed %>>
  <label for="completed">This task is <%= @task_phrase %></label>
</div>

<%= link_to "Delete", task_path(@task),
    method: :delete,
    data: { confirm: "Are you sure you want to delete this task?" } %>

<%= link_to "Back to tasks", tasks_path%>

app/views/tasks/list.html.erb
<h1>My tasks</h1>
<% @tasks.each do |task| %>
<div>
  <input type="checkbox" name="completed" <%= "checked" if task.completed %>>
  <label for="completed"><%= link_to(task.title, task_path(task)) %></label>
</div>
<% end %>

<%= link_to "Add a new task", tasks_new_path%>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>